# main.py
import sys
from lex import lexer
from yacc import parser
from semantic import SemanticAnalyzer
from interpreter import Interpreter



if __name__ == '__main__':
    semantic_analyzer = SemanticAnalyzer()
    interpreter = Interpreter(semantic_analyzer)

    while True:
        try:
            text = input('ticket-lang > ')
        except EOFError:
            break
        if not text:
            continue

        # --- DEBUGGING LEXER TOKENS ---
        #lexer.input(text)  # Give the input text to the lexer
        #for tok in lexer:  # Iterate through tokens generated by lexer
        #    print(tok)      # Print each token object
        # --- DEBUGGING LEXER TOKENS END ---

        result = parser.parse(text, lexer=lexer)

        if result: # Only proceed if parsing was successful
            interpreter.interpret(result)
