
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AVAILABLE BOOKING BOOKINGS BOOKING_REFERENCE CANCEL CONFIRM DATE EVENT_NAME FOR ID INTEGER ON PAY PAYMENT_METHOD QUANTITY RESERVE SHOW STRING TICKET_TYPE USINGprogram : statement_liststatement_list : statement statement_list\n                      | statementstatement : reserve_statement\n                 | confirm_statement\n                 | pay_statement\n                 | cancel_statement\n                 | show_available_statement\n                 | show_bookings_statementreserve_statement : RESERVE TICKET_TYPE FOR EVENT_NAME ON DATE QUANTITY INTEGERconfirm_statement : CONFIRM BOOKING BOOKING_REFERENCEpay_statement : PAY FOR BOOKING BOOKING_REFERENCE USING PAYMENT_METHODcancel_statement : CANCEL BOOKING BOOKING_REFERENCEshow_available_statement : SHOW AVAILABLE TICKET_TYPEshow_bookings_statement : SHOW BOOKINGS'
    
_lr_action_items = {'RESERVE':([0,3,4,5,6,7,8,9,21,23,25,26,32,34,],[10,10,-4,-5,-6,-7,-8,-9,-15,-11,-13,-14,-12,-10,]),'CONFIRM':([0,3,4,5,6,7,8,9,21,23,25,26,32,34,],[11,11,-4,-5,-6,-7,-8,-9,-15,-11,-13,-14,-12,-10,]),'PAY':([0,3,4,5,6,7,8,9,21,23,25,26,32,34,],[12,12,-4,-5,-6,-7,-8,-9,-15,-11,-13,-14,-12,-10,]),'CANCEL':([0,3,4,5,6,7,8,9,21,23,25,26,32,34,],[13,13,-4,-5,-6,-7,-8,-9,-15,-11,-13,-14,-12,-10,]),'SHOW':([0,3,4,5,6,7,8,9,21,23,25,26,32,34,],[14,14,-4,-5,-6,-7,-8,-9,-15,-11,-13,-14,-12,-10,]),'$end':([1,2,3,4,5,6,7,8,9,15,21,23,25,26,32,34,],[0,-1,-3,-4,-5,-6,-7,-8,-9,-2,-15,-11,-13,-14,-12,-10,]),'TICKET_TYPE':([10,20,],[16,26,]),'BOOKING':([11,13,18,],[17,19,24,]),'FOR':([12,16,],[18,22,]),'AVAILABLE':([14,],[20,]),'BOOKINGS':([14,],[21,]),'BOOKING_REFERENCE':([17,19,24,],[23,25,28,]),'EVENT_NAME':([22,],[27,]),'ON':([27,],[29,]),'USING':([28,],[30,]),'DATE':([29,],[31,]),'PAYMENT_METHOD':([30,],[32,]),'QUANTITY':([31,],[33,]),'INTEGER':([33,],[34,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement_list':([0,3,],[2,15,]),'statement':([0,3,],[3,3,]),'reserve_statement':([0,3,],[4,4,]),'confirm_statement':([0,3,],[5,5,]),'pay_statement':([0,3,],[6,6,]),'cancel_statement':([0,3,],[7,7,]),'show_available_statement':([0,3,],[8,8,]),'show_bookings_statement':([0,3,],[9,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','yacc.py',63),
  ('statement_list -> statement statement_list','statement_list',2,'p_statement_list','yacc.py',67),
  ('statement_list -> statement','statement_list',1,'p_statement_list','yacc.py',68),
  ('statement -> reserve_statement','statement',1,'p_statement','yacc.py',75),
  ('statement -> confirm_statement','statement',1,'p_statement','yacc.py',76),
  ('statement -> pay_statement','statement',1,'p_statement','yacc.py',77),
  ('statement -> cancel_statement','statement',1,'p_statement','yacc.py',78),
  ('statement -> show_available_statement','statement',1,'p_statement','yacc.py',79),
  ('statement -> show_bookings_statement','statement',1,'p_statement','yacc.py',80),
  ('reserve_statement -> RESERVE TICKET_TYPE FOR EVENT_NAME ON DATE QUANTITY INTEGER','reserve_statement',8,'p_reserve_statement','yacc.py',84),
  ('confirm_statement -> CONFIRM BOOKING BOOKING_REFERENCE','confirm_statement',3,'p_confirm_statement','yacc.py',88),
  ('pay_statement -> PAY FOR BOOKING BOOKING_REFERENCE USING PAYMENT_METHOD','pay_statement',6,'p_pay_statement','yacc.py',92),
  ('cancel_statement -> CANCEL BOOKING BOOKING_REFERENCE','cancel_statement',3,'p_cancel_statement','yacc.py',96),
  ('show_available_statement -> SHOW AVAILABLE TICKET_TYPE','show_available_statement',3,'p_show_available_statement','yacc.py',100),
  ('show_bookings_statement -> SHOW BOOKINGS','show_bookings_statement',2,'p_show_bookings_statement','yacc.py',104),
]
